name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Run Unit Tests
        run: ./gradlew clean testDebugUnitTest --tests "*"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest
